ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.highloadinvest.gateway.ApplicationKt.module ]
    }
}

clickhouse {
    url = "http://localhost:8123"
    url = ${?CLICKHOUSE_HTTP}
}

redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
}
