# cmake/KernelModule.cmake
# Вспомогательный модуль для сборки Linux kernel modules через Kbuild.
#
# Использование в CMakeLists.txt:
#   include(cmake/KernelModule.cmake)
#   add_kernel_module(
#       NAME       my_driver
#       SOURCE_DIR "${CMAKE_SOURCE_DIR}/kernel"
#       SOURCES    my_driver.c helper.c
#   )
#
# Создаёт цели:
#   <NAME>_kbuild  — вызывает make -C $KDIR M=<SOURCE_DIR> modules
#   <NAME>_clean   — make -C $KDIR M=<SOURCE_DIR> clean

# Находим директорию Kbuild для текущего ядра
execute_process(
    COMMAND uname -r
    OUTPUT_VARIABLE KERNEL_RELEASE
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(KBUILD_DIR "/lib/modules/${KERNEL_RELEASE}/build"
    CACHE PATH "Path to kernel build directory")

if(NOT EXISTS "${KBUILD_DIR}")
    message(WARNING
        "Kernel build dir not found: ${KBUILD_DIR}\n"
        "Install linux-headers-${KERNEL_RELEASE} and set KBUILD_DIR.")
endif()

# ──────────────────────────────────────────────────────────────────────
# add_kernel_module(NAME <name> SOURCE_DIR <dir> SOURCES <file> ...)
# ──────────────────────────────────────────────────────────────────────
function(add_kernel_module)
    cmake_parse_arguments(KM "" "NAME;SOURCE_DIR" "SOURCES" ${ARGN})

    if(NOT KM_NAME OR NOT KM_SOURCE_DIR OR NOT KM_SOURCES)
        message(FATAL_ERROR "add_kernel_module: NAME, SOURCE_DIR, SOURCES are required")
    endif()

    # Генерируем Kbuild-файл в директории исходников модуля
    set(KBUILD_FILE "${KM_SOURCE_DIR}/Kbuild")
    set(OBJ_LIST "")
    foreach(src ${KM_SOURCES})
        string(REGEX REPLACE "\\.c$" ".o" obj "${src}")
        list(APPEND OBJ_LIST "${obj}")
    endforeach()
    list(JOIN OBJ_LIST " " OBJ_STR)

    # Записываем Kbuild только если он изменился (избегаем лишних пересборок)
    file(WRITE "${KBUILD_FILE}.tmp"
        "# Auto-generated by CMake — do not edit\n"
        "obj-m += ${KM_NAME}.o\n"
    )
    if(NOT EXISTS "${KBUILD_FILE}" OR
       NOT "${KBUILD_FILE}.tmp" IS_NEWER_THAN "${KBUILD_FILE}")
        execute_process(
            COMMAND ${CMAKE_COMMAND} -E copy_if_different
                    "${KBUILD_FILE}.tmp" "${KBUILD_FILE}"
        )
    endif()

    # Список абсолютных путей к исходникам (для отслеживания зависимостей)
    set(ABS_SOURCES "")
    foreach(src ${KM_SOURCES})
        list(APPEND ABS_SOURCES "${KM_SOURCE_DIR}/${src}")
    endforeach()

    set(KO_OUTPUT "${KM_SOURCE_DIR}/${KM_NAME}.ko")

    # Основная цель сборки
    add_custom_command(
        OUTPUT  "${KO_OUTPUT}"
        COMMAND ${CMAKE_MAKE_PROGRAM}
                -C "${KBUILD_DIR}"
                M="${KM_SOURCE_DIR}"
                modules
        DEPENDS ${ABS_SOURCES}
        WORKING_DIRECTORY "${KM_SOURCE_DIR}"
        COMMENT "Building kernel module ${KM_NAME}.ko"
        VERBATIM
    )

    add_custom_target("${KM_NAME}_kbuild" ALL
        DEPENDS "${KO_OUTPUT}"
    )

    # Цель очистки
    add_custom_target("${KM_NAME}_clean"
        COMMAND ${CMAKE_MAKE_PROGRAM}
                -C "${KBUILD_DIR}"
                M="${KM_SOURCE_DIR}"
                clean
        WORKING_DIRECTORY "${KM_SOURCE_DIR}"
        COMMENT "Cleaning kernel module ${KM_NAME}"
        VERBATIM
    )

    message(STATUS "Kernel module target: ${KM_NAME}_kbuild → ${KO_OUTPUT}")
endfunction()
