ktor {
    deployment {
        port = 8081
        port = ${?PORT}
    }
    application {
        modules = [ com.highloadinvest.banking.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/highload_invest"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
    maxPoolSize = ${?DATABASE_MAX_POOL_SIZE}
}
